//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        internal static string Aciklama {
            get {
                return ResourceManager.GetString("Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        internal static string AktifMi {
            get {
                return ResourceManager.GetString("AktifMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to almak.
        /// </summary>
        internal static string Almak {
            get {
                return ResourceManager.GetString("Almak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alman.
        /// </summary>
        internal static string Alman {
            get {
                return ResourceManager.GetString("Alman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALMANYA TİCARET VE YATIRIM RAPORU 2020.
        /// </summary>
        internal static string AlmanyaYatirimveTicaretRaporu2020 {
            get {
                return ResourceManager.GetString("AlmanyaYatirimveTicaretRaporu2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt menü mü?.
        /// </summary>
        internal static string AltMenuMu {
            get {
                return ResourceManager.GetString("AltMenuMu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana dizin.
        /// </summary>
        internal static string AnaDizin {
            get {
                return ResourceManager.GetString("AnaDizin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        internal static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        internal static string Ara {
            get {
                return ResourceManager.GetString("Ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avantajlar.
        /// </summary>
        internal static string Avantajlar {
            get {
                return ResourceManager.GetString("Avantajlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        internal static string Baslik {
            get {
                return ResourceManager.GetString("Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        internal static string BeniHatirla {
            get {
                return ResourceManager.GetString("BeniHatirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Mio € kadar.
        /// </summary>
        internal static string BesMilyonEuroKadar {
            get {
                return ResourceManager.GetString("BesMilyonEuroKadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi Notları.
        /// </summary>
        internal static string BilgiNotlari {
            get {
                return ResourceManager.GetString("BilgiNotlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bireysel Başvuru.
        /// </summary>
        internal static string BireyselBasvuru {
            get {
                return ResourceManager.GetString("BireyselBasvuru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En son gelişmelerden ve fırsatlardan haberdar olmak için bültenimize kaydolun..
        /// </summary>
        internal static string BultenSonGelismeler {
            get {
                return ResourceManager.GetString("BultenSonGelismeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri Gizliliği ve Tüzük&apos;ü buraya tıklayarak kabul edebilirsiniz..
        /// </summary>
        internal static string BurayaTiklayarakKabulEdebilirsiniz {
            get {
                return ResourceManager.GetString("BurayaTiklayarakKabulEdebilirsiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Formu.
        /// </summary>
        internal static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        internal static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COVID-19.
        /// </summary>
        internal static string Covid19 {
            get {
                return ResourceManager.GetString("Covid19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Fazla.
        /// </summary>
        internal static string DahaFazla {
            get {
                return ResourceManager.GetString("DahaFazla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetim Paneli.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri koruma onayı.
        /// </summary>
        internal static string DataPolicyApprove {
            get {
                return ResourceManager.GetString("DataPolicyApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet, gizlilik politikasını kabul ediyorum.
        /// </summary>
        internal static string DataPolicyApproveText {
            get {
                return ResourceManager.GetString("DataPolicyApproveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri koruma düzenlemelerini www.td-ihk.de/tr/sayfalar/gizlilik-politikasi adresinde okudum ve düzenlemeleri kabul ediyorum..
        /// </summary>
        internal static string DataPolicyReadAndApproveText {
            get {
                return ResourceManager.GetString("DataPolicyReadAndApproveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dış Ticaret Portalı.
        /// </summary>
        internal static string DisTicaretPortali {
            get {
                return ResourceManager.GetString("DisTicaretPortali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (4.800 € / Yıllık).
        /// </summary>
        internal static string DortBinSekizYuzEuroYillik {
            get {
                return ResourceManager.GetString("DortBinSekizYuzEuroYillik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya.
        /// </summary>
        internal static string Dosya {
            get {
                return ResourceManager.GetString("Dosya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Boyutu.
        /// </summary>
        internal static string DosyaBoyutu {
            get {
                return ResourceManager.GetString("DosyaBoyutu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Seçiniz.
        /// </summary>
        internal static string DosyaSeciniz {
            get {
                return ResourceManager.GetString("DosyaSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Tipi.
        /// </summary>
        internal static string DosyaTipi {
            get {
                return ResourceManager.GetString("DosyaTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya URL.
        /// </summary>
        internal static string DosyaURL {
            get {
                return ResourceManager.GetString("DosyaURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Uzantısı.
        /// </summary>
        internal static string DosyaUzantisi {
            get {
                return ResourceManager.GetString("DosyaUzantisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektronik İmza.
        /// </summary>
        internal static string ElektronikImza {
            get {
                return ResourceManager.GetString("ElektronikImza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Adres.
        /// </summary>
        internal static string EmailAdres {
            get {
                return ResourceManager.GetString("EmailAdres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email veya Kullanıcı Adı.
        /// </summary>
        internal static string EmailKullaniciAdi {
            get {
                return ResourceManager.GetString("EmailKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüzük.
        /// </summary>
        internal static string EsasSozlesme {
            get {
                return ResourceManager.GetString("EsasSozlesme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiketler.
        /// </summary>
        internal static string Etiketler {
            get {
                return ResourceManager.GetString("Etiketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Açıklaması.
        /// </summary>
        internal static string EtkinlikAciklamasi {
            get {
                return ResourceManager.GetString("EtkinlikAciklamasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dijital Arşiv.
        /// </summary>
        internal static string EtkinlikArsivi {
            get {
                return ResourceManager.GetString("EtkinlikArsivi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Başlığı.
        /// </summary>
        internal static string EtkinlikBasligi {
            get {
                return ResourceManager.GetString("EtkinlikBasligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Dili.
        /// </summary>
        internal static string EtkinlikDili {
            get {
                return ResourceManager.GetString("EtkinlikDili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Ekle.
        /// </summary>
        internal static string EtkinlikEkle {
            get {
                return ResourceManager.GetString("EtkinlikEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Haberi.
        /// </summary>
        internal static string EtkinlikHaberiMi {
            get {
                return ResourceManager.GetString("EtkinlikHaberiMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Kategori Ekle.
        /// </summary>
        internal static string EtkinlikKategoriEkle {
            get {
                return ResourceManager.GetString("EtkinlikKategoriEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Kayıt ID.
        /// </summary>
        internal static string EtkinlikKayitID {
            get {
                return ResourceManager.GetString("EtkinlikKayitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Kayıt Listesi.
        /// </summary>
        internal static string EtkinlikKayitListesi {
            get {
                return ResourceManager.GetString("EtkinlikKayitListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Kontenjanı.
        /// </summary>
        internal static string EtkinlikKontenjani {
            get {
                return ResourceManager.GetString("EtkinlikKontenjani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Kritik Kontenjan.
        /// </summary>
        internal static string EtkinlikKritikKontenjan {
            get {
                return ResourceManager.GetString("EtkinlikKritikKontenjan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlikler.
        /// </summary>
        internal static string Etkinlikler {
            get {
                return ResourceManager.GetString("Etkinlikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinliklerimiz.
        /// </summary>
        internal static string Etkinliklerimiz {
            get {
                return ResourceManager.GetString("Etkinliklerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Listesi.
        /// </summary>
        internal static string EtkinlikListesi {
            get {
                return ResourceManager.GetString("EtkinlikListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Özellikleri.
        /// </summary>
        internal static string EtkinlikOzellikleri {
            get {
                return ResourceManager.GetString("EtkinlikOzellikleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Saati.
        /// </summary>
        internal static string EtkinlikSaati {
            get {
                return ResourceManager.GetString("EtkinlikSaati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Takvimi.
        /// </summary>
        internal static string EtkinlikTakvimi {
            get {
                return ResourceManager.GetString("EtkinlikTakvimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Tarihi.
        /// </summary>
        internal static string EtkinlikTarihi {
            get {
                return ResourceManager.GetString("EtkinlikTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev Numarası.
        /// </summary>
        internal static string EvNumarasi {
            get {
                return ResourceManager.GetString("EvNumarasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eylemler.
        /// </summary>
        internal static string Eylemler {
            get {
                return ResourceManager.GetString("Eylemler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Adı.
        /// </summary>
        internal static string FirmaAdi {
            get {
                return ResourceManager.GetString("FirmaAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaya kabul için, Ana Sözleşme&apos;nin 7 (1) Bölümüne göre, bir başvuru ve katkı payının ödenmesi gerekmektedir. Yönetim kurulu yazılı başvuruya karar verir. Başvuru sahibine karar yazılı olarak bildirilecektir. Tüzüğün § 8 II&apos;ye göre, her üye herhangi bir zamanda odadan istifa etme hakkına sahiptir. Üyenin istifa beyanının yazılı olarak yönetim kuruluna sunulması zorunludur. Üye, istifasına rağmen içinde bulunduğu takvim yılı için katkı payını ödemekle yükümlüdür..
        /// </summary>
        internal static string FormMetin {
            get {
                return ResourceManager.GetString("FormMetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçmiş Etkinlikler.
        /// </summary>
        internal static string GecmisEtkinlikler {
            get {
                return ResourceManager.GetString("GecmisEtkinlikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelecek Etkinlikler.
        /// </summary>
        internal static string GelecekEtkinlikler {
            get {
                return ResourceManager.GetString("GelecekEtkinlikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        internal static string Geri {
            get {
                return ResourceManager.GetString("Geri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş-Çıkış Kuralları.
        /// </summary>
        internal static string GirisCikisKurallari {
            get {
                return ResourceManager.GetString("GirisCikisKurallari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik.
        /// </summary>
        internal static string Gizlilik {
            get {
                return ResourceManager.GetString("Gizlilik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik Politikası.
        /// </summary>
        internal static string GizlilikPolitikasi {
            get {
                return ResourceManager.GetString("GizlilikPolitikasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik Politikası ve Esas Sözleşme.
        /// </summary>
        internal static string GizlilikPolitikasiveEsasSozlesme {
            get {
                return ResourceManager.GetString("GizlilikPolitikasiveEsasSozlesme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        internal static string Gonder {
            get {
                return ResourceManager.GetString("Gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görsel Listesi.
        /// </summary>
        internal static string GorselListesi {
            get {
                return ResourceManager.GetString("GorselListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görsel Seçiniz.
        /// </summary>
        internal static string GorselSeciniz {
            get {
                return ResourceManager.GetString("GorselSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görsel Yükle.
        /// </summary>
        internal static string GorselYukle {
            get {
                return ResourceManager.GetString("GorselYukle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string Guncelle {
            get {
                return ResourceManager.GetString("Guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme Tarihi.
        /// </summary>
        internal static string GuncellemeTarihi {
            get {
                return ResourceManager.GetString("GuncellemeTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleyen.
        /// </summary>
        internal static string Guncelleyen {
            get {
                return ResourceManager.GetString("Guncelleyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Açıklaması.
        /// </summary>
        internal static string HaberAciklamasi {
            get {
                return ResourceManager.GetString("HaberAciklamasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Başlık.
        /// </summary>
        internal static string HaberBaslik {
            get {
                return ResourceManager.GetString("HaberBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Dili.
        /// </summary>
        internal static string HaberDili {
            get {
                return ResourceManager.GetString("HaberDili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Ekle.
        /// </summary>
        internal static string HaberEkle {
            get {
                return ResourceManager.GetString("HaberEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber ID.
        /// </summary>
        internal static string HaberID {
            get {
                return ResourceManager.GetString("HaberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Identifier.
        /// </summary>
        internal static string HaberIdentifier {
            get {
                return ResourceManager.GetString("HaberIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Ekle.
        /// </summary>
        internal static string HaberKategoriEkle {
            get {
                return ResourceManager.GetString("HaberKategoriEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        internal static string Haberler {
            get {
                return ResourceManager.GetString("Haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Listesi.
        /// </summary>
        internal static string HaberListesi {
            get {
                return ResourceManager.GetString("HaberListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        internal static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetlerimiz.
        /// </summary>
        internal static string Hizmetlerimiz {
            get {
                return ResourceManager.GetString("Hizmetlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        internal static string Hosgeldiniz {
            get {
                return ResourceManager.GetString("Hosgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier Seç.
        /// </summary>
        internal static string IdentifierSec {
            get {
                return ResourceManager.GetString("IdentifierSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (2.400 €/ Yıllık).
        /// </summary>
        internal static string IkiBinDortYuzEuroYillik {
            get {
                return ResourceManager.GetString("IkiBinDortYuzEuroYillik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Formu.
        /// </summary>
        internal static string IletisimFormu {
            get {
                return ResourceManager.GetString("IletisimFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        internal static string Isim {
            get {
                return ResourceManager.GetString("Isim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Teklifine Git.
        /// </summary>
        internal static string IsTeklifi {
            get {
                return ResourceManager.GetString("IsTeklifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Teklifi Düzenle.
        /// </summary>
        internal static string IsTeklifiDuzenle {
            get {
                return ResourceManager.GetString("IsTeklifiDuzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Teklifi Ekle.
        /// </summary>
        internal static string IsTeklifiEkle {
            get {
                return ResourceManager.GetString("IsTeklifiEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Teklifi ID.
        /// </summary>
        internal static string IsTeklifiID {
            get {
                return ResourceManager.GetString("IsTeklifiID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Teklifi Listesi.
        /// </summary>
        internal static string IsTeklifiListesi {
            get {
                return ResourceManager.GetString("IsTeklifiListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Teklifi.
        /// </summary>
        internal static string IsTeklifiMetin {
            get {
                return ResourceManager.GetString("IsTeklifiMetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstek Listesi.
        /// </summary>
        internal static string IstekListesi {
            get {
                return ResourceManager.GetString("IstekListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsterseniz üye olabilir veya üye olmadan yayın ücretinin ne kadar olduğunu sorabilirsiniz..
        /// </summary>
        internal static string JobageboteMetin {
            get {
                return ResourceManager.GetString("JobageboteMetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Adı.
        /// </summary>
        internal static string KategoriAdi {
            get {
                return ResourceManager.GetString("KategoriAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Ayarları.
        /// </summary>
        internal static string KategoriAyarlari {
            get {
                return ResourceManager.GetString("KategoriAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Dili.
        /// </summary>
        internal static string KategoriDili {
            get {
                return ResourceManager.GetString("KategoriDili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Seçiniz.
        /// </summary>
        internal static string KategoriSeciniz {
            get {
                return ResourceManager.GetString("KategoriSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string Kaydet {
            get {
                return ResourceManager.GetString("Kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol.
        /// </summary>
        internal static string Kaydol {
            get {
                return ResourceManager.GetString("Kaydol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt.
        /// </summary>
        internal static string Kayit {
            get {
                return ResourceManager.GetString("Kayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        internal static string KayitOl {
            get {
                return ResourceManager.GetString("KayitOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasör.
        /// </summary>
        internal static string Klasor {
            get {
                return ResourceManager.GetString("Klasor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Künye.
        /// </summary>
        internal static string Kunye {
            get {
                return ResourceManager.GetString("Kunye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal Başvuru.
        /// </summary>
        internal static string KurumBasvurusu {
            get {
                return ResourceManager.GetString("KurumBasvurusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurum Bilgisi Düzenle.
        /// </summary>
        internal static string KurumBilgisiDuzenle {
            get {
                return ResourceManager.GetString("KurumBilgisiDuzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurum Bilgisi Oluştur.
        /// </summary>
        internal static string KurumBilgisiOlustur {
            get {
                return ResourceManager.GetString("KurumBilgisiOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logonuz buraya gelecek.
        /// </summary>
        internal static string LogonuzBurayaGelecek {
            get {
                return ResourceManager.GetString("LogonuzBurayaGelecek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokasyon.
        /// </summary>
        internal static string Lokasyon {
            get {
                return ResourceManager.GetString("Lokasyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen şirket logonuzu buraya yükleyin..
        /// </summary>
        internal static string LutfenSırketLogonuzuBurayaYukleyin {
            get {
                return ResourceManager.GetString("LutfenSırketLogonuzuBurayaYukleyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail zaten kayıtlı!.
        /// </summary>
        internal static string MailAdresiKayitli {
            get {
                return ResourceManager.GetString("MailAdresiKayitli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail listesine eklendi..
        /// </summary>
        internal static string MailListesineEklendi {
            get {
                return ResourceManager.GetString("MailListesineEklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail listesine eklenemedi!.
        /// </summary>
        internal static string MailListesineEklenemedi {
            get {
                return ResourceManager.GetString("MailListesineEklenemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Adı.
        /// </summary>
        internal static string MenuAdi {
            get {
                return ResourceManager.GetString("MenuAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Adı Giriniz.
        /// </summary>
        internal static string MenuAdiGiriniz {
            get {
                return ResourceManager.GetString("MenuAdiGiriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Dili Seçiniz.
        /// </summary>
        internal static string MenuDiliSeciniz {
            get {
                return ResourceManager.GetString("MenuDiliSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Ekle.
        /// </summary>
        internal static string MenuEkle {
            get {
                return ResourceManager.GetString("MenuEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Elemanı Ekle.
        /// </summary>
        internal static string MenuElemanEkle {
            get {
                return ResourceManager.GetString("MenuElemanEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Elemanı Düzenle.
        /// </summary>
        internal static string MenuElemaniDuzenle {
            get {
                return ResourceManager.GetString("MenuElemaniDuzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Eleman Listesi.
        /// </summary>
        internal static string MenuElemanListesi {
            get {
                return ResourceManager.GetString("MenuElemanListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü ID.
        /// </summary>
        internal static string MenuID {
            get {
                return ResourceManager.GetString("MenuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menüler.
        /// </summary>
        internal static string Menuler {
            get {
                return ResourceManager.GetString("Menuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Level.
        /// </summary>
        internal static string MenuLevel {
            get {
                return ResourceManager.GetString("MenuLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Listesi.
        /// </summary>
        internal static string MenuListesi {
            get {
                return ResourceManager.GetString("MenuListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Seçiniz.
        /// </summary>
        internal static string MenuSeciniz {
            get {
                return ResourceManager.GetString("MenuSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Sırası.
        /// </summary>
        internal static string MenuSirasi {
            get {
                return ResourceManager.GetString("MenuSirasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Tipi.
        /// </summary>
        internal static string MenuTip {
            get {
                return ResourceManager.GetString("MenuTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturan.
        /// </summary>
        internal static string Olusturan {
            get {
                return ResourceManager.GetString("Olusturan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulma Tarihi.
        /// </summary>
        internal static string OlusturulmaTarihi {
            get {
                return ResourceManager.GetString("OlusturulmaTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.000 € / yıl.
        /// </summary>
        internal static string OnBinEuroYillik {
            get {
                return ResourceManager.GetString("OnBinEuroYillik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öne Çıkan Görsel Belirle.
        /// </summary>
        internal static string OneCikanGorsel {
            get {
                return ResourceManager.GetString("OneCikanGorsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öne çıkarılmış görsel belirle.
        /// </summary>
        internal static string OneCikanGorselBelirle {
            get {
                return ResourceManager.GetString("OneCikanGorselBelirle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1,200 € / Yıllık).
        /// </summary>
        internal static string OnIkiBinEuroYillik {
            get {
                return ResourceManager.GetString("OnIkiBinEuroYillik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önizleme.
        /// </summary>
        internal static string Onizleme {
            get {
                return ResourceManager.GetString("Onizleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Üyeliğin 10 koltuğundan birinde yer almak ister misiniz?.
        /// </summary>
        internal static string OnKoltugundanBirisiniIsterMisiniz {
            get {
                return ResourceManager.GetString("OnKoltugundanBirisiniIsterMisiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Üyeliğin 10 koltuğundan birinde yer almak ister misiniz?.
        /// </summary>
        internal static string OnKoltuktanBirisiniIsterMisiniz {
            get {
                return ResourceManager.GetString("OnKoltuktanBirisiniIsterMisiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Meeting.
        /// </summary>
        internal static string OnlineMeeting {
            get {
                return ResourceManager.GetString("OnlineMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özet.
        /// </summary>
        internal static string Ozet {
            get {
                return ResourceManager.GetString("Ozet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pazara Giriş.
        /// </summary>
        internal static string PazaraGiris {
            get {
                return ResourceManager.GetString("PazaraGiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast Açıklaması.
        /// </summary>
        internal static string PodcastAciklamasi {
            get {
                return ResourceManager.GetString("PodcastAciklamasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast Başlık.
        /// </summary>
        internal static string PodcastBaslik {
            get {
                return ResourceManager.GetString("PodcastBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast Dili.
        /// </summary>
        internal static string PodcastDili {
            get {
                return ResourceManager.GetString("PodcastDili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast Dosyası.
        /// </summary>
        internal static string PodcastDosyasi {
            get {
                return ResourceManager.GetString("PodcastDosyasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast Dosya Yolu.
        /// </summary>
        internal static string PodcastDosyaYolu {
            get {
                return ResourceManager.GetString("PodcastDosyaYolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast Düzenle.
        /// </summary>
        internal static string PodcastDuzenle {
            get {
                return ResourceManager.GetString("PodcastDuzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast Ekle.
        /// </summary>
        internal static string PodcastEkle {
            get {
                return ResourceManager.GetString("PodcastEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast ID.
        /// </summary>
        internal static string PodcastID {
            get {
                return ResourceManager.GetString("PodcastID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast Listesi.
        /// </summary>
        internal static string PodcastListesi {
            get {
                return ResourceManager.GetString("PodcastListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Kodu.
        /// </summary>
        internal static string PostaKodu {
            get {
                return ResourceManager.GetString("PostaKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozisyon.
        /// </summary>
        internal static string Pozisyon {
            get {
                return ResourceManager.GetString("Pozisyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozisyon Açıklaması.
        /// </summary>
        internal static string PozisyonAciklamasi {
            get {
                return ResourceManager.GetString("PozisyonAciklamasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik avantajları hakkında daha fazla bilgi edinin.
        /// </summary>
        internal static string PremiumUyeAvantajlariDetayliBilgi {
            get {
                return ResourceManager.GetString("PremiumUyeAvantajlariDetayliBilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Üyeler.
        /// </summary>
        internal static string PremiumUyeler {
            get {
                return ResourceManager.GetString("PremiumUyeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Üyeliğin.
        /// </summary>
        internal static string PremiumUyeligin {
            get {
                return ResourceManager.GetString("PremiumUyeligin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium-Üyelik.
        /// </summary>
        internal static string PremiumUyelik {
            get {
                return ResourceManager.GetString("PremiumUyelik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Üyelik Ücreti.
        /// </summary>
        internal static string PremiumUyelikUcreti {
            get {
                return ResourceManager.GetString("PremiumUyelikUcreti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Oluştur.
        /// </summary>
        internal static string RaporOlustur {
            get {
                return ResourceManager.GetString("RaporOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Başlık.
        /// </summary>
        internal static string SayfaBaslik {
            get {
                return ResourceManager.GetString("SayfaBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Dili.
        /// </summary>
        internal static string SayfaDili {
            get {
                return ResourceManager.GetString("SayfaDili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Ekle.
        /// </summary>
        internal static string SayfaEkle {
            get {
                return ResourceManager.GetString("SayfaEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa ID.
        /// </summary>
        internal static string SayfaID {
            get {
                return ResourceManager.GetString("SayfaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Identifier.
        /// </summary>
        internal static string SayfaIdentifier {
            get {
                return ResourceManager.GetString("SayfaIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Kategori Ekle.
        /// </summary>
        internal static string SayfaKategoriEkle {
            get {
                return ResourceManager.GetString("SayfaKategoriEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        internal static string Sayfalar {
            get {
                return ResourceManager.GetString("Sayfalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Listesi.
        /// </summary>
        internal static string SayfaListesi {
            get {
                return ResourceManager.GetString("SayfaListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Özellikleri.
        /// </summary>
        internal static string SayfaOzellikleri {
            get {
                return ResourceManager.GetString("SayfaOzellikleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Seçiniz.
        /// </summary>
        internal static string SayfaSeciniz {
            get {
                return ResourceManager.GetString("SayfaSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seç.
        /// </summary>
        internal static string Sec {
            get {
                return ResourceManager.GetString("Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO Anahtar Kelimeleri.
        /// </summary>
        internal static string SeoAnahtarKelimeleri {
            get {
                return ResourceManager.GetString("SeoAnahtarKelimeleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO Ayarları.
        /// </summary>
        internal static string SeoAyarlari {
            get {
                return ResourceManager.GetString("SeoAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seo Link.
        /// </summary>
        internal static string SeoLink {
            get {
                return ResourceManager.GetString("SeoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum.
        /// </summary>
        internal static string SifremiUnuttum {
            get {
                return ResourceManager.GetString("SifremiUnuttum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket.
        /// </summary>
        internal static string Sirket {
            get {
                return ResourceManager.GetString("Sirket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Adı.
        /// </summary>
        internal static string SliderAdi {
            get {
                return ResourceManager.GetString("SliderAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Alanı Seç.
        /// </summary>
        internal static string SliderAlaniSec {
            get {
                return ResourceManager.GetString("SliderAlaniSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Dili.
        /// </summary>
        internal static string SliderDili {
            get {
                return ResourceManager.GetString("SliderDili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Ekle.
        /// </summary>
        internal static string SliderEkle {
            get {
                return ResourceManager.GetString("SliderEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Elemanları.
        /// </summary>
        internal static string SliderElemanlari {
            get {
                return ResourceManager.GetString("SliderElemanlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Görsel Yükle.
        /// </summary>
        internal static string SliderGorselYukle {
            get {
                return ResourceManager.GetString("SliderGorselYukle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider İçerik Düzenle.
        /// </summary>
        internal static string SliderIcerikDuzenle {
            get {
                return ResourceManager.GetString("SliderIcerikDuzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider İçerik Ekle.
        /// </summary>
        internal static string SliderIcerikEkle {
            get {
                return ResourceManager.GetString("SliderIcerikEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider ID.
        /// </summary>
        internal static string SliderID {
            get {
                return ResourceManager.GetString("SliderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Listesi.
        /// </summary>
        internal static string SliderListesi {
            get {
                return ResourceManager.GetString("SliderListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Sırası.
        /// </summary>
        internal static string SliderSirasi {
            get {
                return ResourceManager.GetString("SliderSirasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider URL.
        /// </summary>
        internal static string SliderUrl {
            get {
                return ResourceManager.GetString("SliderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sokak.
        /// </summary>
        internal static string Sokak {
            get {
                return ResourceManager.GetString("Sokak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonuçlar.
        /// </summary>
        internal static string Sonuclar {
            get {
                return ResourceManager.GetString("Sonuclar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı.
        /// </summary>
        internal static string Soyadi {
            get {
                return ResourceManager.GetString("Soyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        internal static string Tarih {
            get {
                return ResourceManager.GetString("Tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Olarak Kaydet.
        /// </summary>
        internal static string TaslakOlarakKaydet {
            get {
                return ResourceManager.GetString("TaslakOlarakKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavsiye edebileceğiniz üyeler.
        /// </summary>
        internal static string TavsiyeEdeceginizDigerOdaUyeleri {
            get {
                return ResourceManager.GetString("TavsiyeEdeceginizDigerOdaUyeleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türk-Alman Ticaret ve Sanayi Odası&apos;na üye olmak istiyorum.
        /// </summary>
        internal static string TDIHKUyeligineBasvuruyorum {
            get {
                return ResourceManager.GetString("TDIHKUyeligineBasvuruyorum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temsilci.
        /// </summary>
        internal static string Temsilci {
            get {
                return ResourceManager.GetString("Temsilci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticaret odasından nasıl haberdar oldunuz.
        /// </summary>
        internal static string TicaretOdasiMetin {
            get {
                return ResourceManager.GetString("TicaretOdasiMetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümünü Göster.
        /// </summary>
        internal static string TumunuGoster {
            get {
                return ResourceManager.GetString("TumunuGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ücretsizdir.
        /// </summary>
        internal static string Ucretsizdir {
            get {
                return ResourceManager.GetString("Ucretsizdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üst Menü Seçiniz.
        /// </summary>
        internal static string UstMenuSeciniz {
            get {
                return ResourceManager.GetString("UstMenuSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Adres.
        /// </summary>
        internal static string UyeAdres {
            get {
                return ResourceManager.GetString("UyeAdres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ara.
        /// </summary>
        internal static string UyeAra {
            get {
                return ResourceManager.GetString("UyeAra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Düzenle.
        /// </summary>
        internal static string UyeDuzenle {
            get {
                return ResourceManager.GetString("UyeDuzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ekle.
        /// </summary>
        internal static string UyeEkle {
            get {
                return ResourceManager.GetString("UyeEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Email.
        /// </summary>
        internal static string UyeEmail {
            get {
                return ResourceManager.GetString("UyeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye ID.
        /// </summary>
        internal static string UyeID {
            get {
                return ResourceManager.GetString("UyeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeler.
        /// </summary>
        internal static string Uyeler {
            get {
                return ResourceManager.GetString("Uyeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelerimiz için bu.
        /// </summary>
        internal static string UyelerimizIcinBu {
            get {
                return ResourceManager.GetString("UyelerimizIcinBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik.
        /// </summary>
        internal static string Uyelik {
            get {
                return ResourceManager.GetString("Uyelik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik Başvurusu.
        /// </summary>
        internal static string UyelikBasvurusu {
            get {
                return ResourceManager.GetString("UyelikBasvurusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Listesi.
        /// </summary>
        internal static string UyeListesi {
            get {
                return ResourceManager.GetString("UyeListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Logo.
        /// </summary>
        internal static string UyeLogo {
            get {
                return ResourceManager.GetString("UyeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye mi?.
        /// </summary>
        internal static string UyeMi {
            get {
                return ResourceManager.GetString("UyeMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Seçiniz.
        /// </summary>
        internal static string UyeSeciniz {
            get {
                return ResourceManager.GetString("UyeSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Telefon.
        /// </summary>
        internal static string UyeTelefon {
            get {
                return ResourceManager.GetString("UyeTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ünvan.
        /// </summary>
        internal static string UyeUnvan {
            get {
                return ResourceManager.GetString("UyeUnvan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Website.
        /// </summary>
        internal static string UyeWebsite {
            get {
                return ResourceManager.GetString("UyeWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri Gizliliği.
        /// </summary>
        internal static string VeriGizlilik {
            get {
                return ResourceManager.GetString("VeriGizlilik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD-IHK&apos;nın verilerinizi nasıl işlediğine ilişkin bilgiler Veri Gizliliği sayfasında bulunabilir.
        /// </summary>
        internal static string VeriIsleme {
            get {
                return ResourceManager.GetString("VeriIsleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ortağımız GTAI&apos;den iş bilgileri alın. Üyeliğin avantajları hakkında daha fazla bilgi edinin..
        /// </summary>
        internal static string VorteilleMetin {
            get {
                return ResourceManager.GetString("VorteilleMetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yalnızca.
        /// </summary>
        internal static string Yalnizca {
            get {
                return ResourceManager.GetString("Yalnizca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayınla.
        /// </summary>
        internal static string Yayimla {
            get {
                return ResourceManager.GetString("Yayimla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayınlarımız.
        /// </summary>
        internal static string Yayinlarimiz {
            get {
                return ResourceManager.GetString("Yayinlarimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yer.
        /// </summary>
        internal static string Yer {
            get {
                return ResourceManager.GetString("Yer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yer kaldı.
        /// </summary>
        internal static string YerKaldi {
            get {
                return ResourceManager.GetString("YerKaldi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yer, Zaman.
        /// </summary>
        internal static string YerZaman {
            get {
                return ResourceManager.GetString("YerZaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 Mio € kadar.
        /// </summary>
        internal static string YirmiMilyonEuroKadar {
            get {
                return ResourceManager.GetString("YirmiMilyonEuroKadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 Mio € üzerinde.
        /// </summary>
        internal static string YirmiMilyonEuroUzerinde {
            get {
                return ResourceManager.GetString("YirmiMilyonEuroUzerinde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetim Paneli.
        /// </summary>
        internal static string YonetimPaneli {
            get {
                return ResourceManager.GetString("YonetimPaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız.
        /// </summary>
        internal static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
    }
}
