//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to almak.
        /// </summary>
        internal static string Almak {
            get {
                return ResourceManager.GetString("Almak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alman.
        /// </summary>
        internal static string Alman {
            get {
                return ResourceManager.GetString("Alman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALMANYA TİCARET VE YATIRIM RAPORU 2020.
        /// </summary>
        internal static string AlmanyaYatirimveTicaretRaporu2020 {
            get {
                return ResourceManager.GetString("AlmanyaYatirimveTicaretRaporu2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        internal static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        internal static string Ara {
            get {
                return ResourceManager.GetString("Ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avantajlar.
        /// </summary>
        internal static string Avantajlar {
            get {
                return ResourceManager.GetString("Avantajlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        internal static string Baslik {
            get {
                return ResourceManager.GetString("Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        internal static string BeniHatirla {
            get {
                return ResourceManager.GetString("BeniHatirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi Notları.
        /// </summary>
        internal static string BilgiNotlari {
            get {
                return ResourceManager.GetString("BilgiNotlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bireysel Başvuru.
        /// </summary>
        internal static string BireyselBasvuru {
            get {
                return ResourceManager.GetString("BireyselBasvuru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En son gelismelerden ve firsatlardan haberdar olmak için bültenimize kaydolun..
        /// </summary>
        internal static string BultenSonGelismeler {
            get {
                return ResourceManager.GetString("BultenSonGelismeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buraya tıklayarak kabul edebilirsiniz..
        /// </summary>
        internal static string BurayaTiklayarakKabulEdebilirsiniz {
            get {
                return ResourceManager.GetString("BurayaTiklayarakKabulEdebilirsiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COVID-19.
        /// </summary>
        internal static string Covid19 {
            get {
                return ResourceManager.GetString("Covid19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Fazla.
        /// </summary>
        internal static string DahaFazla {
            get {
                return ResourceManager.GetString("DahaFazla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetim Paneli.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dış Ticaret Portalı.
        /// </summary>
        internal static string DisTicaretPortali {
            get {
                return ResourceManager.GetString("DisTicaretPortali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Seçiniz.
        /// </summary>
        internal static string DosyaSeciniz {
            get {
                return ResourceManager.GetString("DosyaSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektronik İmza.
        /// </summary>
        internal static string ElektronikImza {
            get {
                return ResourceManager.GetString("ElektronikImza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Adres.
        /// </summary>
        internal static string EmailAdres {
            get {
                return ResourceManager.GetString("EmailAdres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email veya Kullanıcı Adı.
        /// </summary>
        internal static string EmailKullaniciAdi {
            get {
                return ResourceManager.GetString("EmailKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiketler.
        /// </summary>
        internal static string Etiketler {
            get {
                return ResourceManager.GetString("Etiketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Açıklaması.
        /// </summary>
        internal static string EtkinlikAciklamasi {
            get {
                return ResourceManager.GetString("EtkinlikAciklamasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Ekle.
        /// </summary>
        internal static string EtkinlikEkle {
            get {
                return ResourceManager.GetString("EtkinlikEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Kontenjanı.
        /// </summary>
        internal static string EtkinlikKontenjani {
            get {
                return ResourceManager.GetString("EtkinlikKontenjani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Kritik Kontenjan.
        /// </summary>
        internal static string EtkinlikKritikKontenjan {
            get {
                return ResourceManager.GetString("EtkinlikKritikKontenjan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlikler.
        /// </summary>
        internal static string Etkinlikler {
            get {
                return ResourceManager.GetString("Etkinlikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinliklerimiz.
        /// </summary>
        internal static string Etkinliklerimiz {
            get {
                return ResourceManager.GetString("Etkinliklerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Listesi.
        /// </summary>
        internal static string EtkinlikListesi {
            get {
                return ResourceManager.GetString("EtkinlikListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Özellikleri.
        /// </summary>
        internal static string EtkinlikOzellikleri {
            get {
                return ResourceManager.GetString("EtkinlikOzellikleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Saati.
        /// </summary>
        internal static string EtkinlikSaati {
            get {
                return ResourceManager.GetString("EtkinlikSaati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Takvimi.
        /// </summary>
        internal static string EtkinlikTakvimi {
            get {
                return ResourceManager.GetString("EtkinlikTakvimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Tarihi.
        /// </summary>
        internal static string EtkinlikTarihi {
            get {
                return ResourceManager.GetString("EtkinlikTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev Numarası.
        /// </summary>
        internal static string EvNumarasi {
            get {
                return ResourceManager.GetString("EvNumarasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eylemler.
        /// </summary>
        internal static string Eylemler {
            get {
                return ResourceManager.GetString("Eylemler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Adı.
        /// </summary>
        internal static string FirmaAdi {
            get {
                return ResourceManager.GetString("FirmaAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçmiş Etkinlikler.
        /// </summary>
        internal static string GecmisEtkinlikler {
            get {
                return ResourceManager.GetString("GecmisEtkinlikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelecek Etkinlikler.
        /// </summary>
        internal static string GelecekEtkinlikler {
            get {
                return ResourceManager.GetString("GelecekEtkinlikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş-Çıkış Kuralları.
        /// </summary>
        internal static string GirisCikisKurallari {
            get {
                return ResourceManager.GetString("GirisCikisKurallari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik.
        /// </summary>
        internal static string Gizlilik {
            get {
                return ResourceManager.GetString("Gizlilik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik Politikası ve Esas Sözleşme.
        /// </summary>
        internal static string GizlilikPolitikasiveEsasSozlesme {
            get {
                return ResourceManager.GetString("GizlilikPolitikasiveEsasSozlesme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        internal static string Gonder {
            get {
                return ResourceManager.GetString("Gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string Guncelle {
            get {
                return ResourceManager.GetString("Guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Ekle.
        /// </summary>
        internal static string HaberEkle {
            get {
                return ResourceManager.GetString("HaberEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        internal static string Haberler {
            get {
                return ResourceManager.GetString("Haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Listesi.
        /// </summary>
        internal static string HaberListesi {
            get {
                return ResourceManager.GetString("HaberListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        internal static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetlerimiz.
        /// </summary>
        internal static string Hizmetlerimiz {
            get {
                return ResourceManager.GetString("Hizmetlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        internal static string Hosgeldiniz {
            get {
                return ResourceManager.GetString("Hosgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim (Form).
        /// </summary>
        internal static string IletisimFormu {
            get {
                return ResourceManager.GetString("IletisimFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        internal static string Isim {
            get {
                return ResourceManager.GetString("Isim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Teklifine Git.
        /// </summary>
        internal static string IsTeklifi {
            get {
                return ResourceManager.GetString("IsTeklifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstek Listesi.
        /// </summary>
        internal static string IstekListesi {
            get {
                return ResourceManager.GetString("IstekListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsterseniz üye olabilir veya üye olmadan yayın ücretinin ne kadar olduğunu sorabilirsiniz..
        /// </summary>
        internal static string JobageboteMetin {
            get {
                return ResourceManager.GetString("JobageboteMetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Ayarları.
        /// </summary>
        internal static string KategoriAyarlari {
            get {
                return ResourceManager.GetString("KategoriAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Seçiniz.
        /// </summary>
        internal static string KategoriSeciniz {
            get {
                return ResourceManager.GetString("KategoriSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol.
        /// </summary>
        internal static string Kaydol {
            get {
                return ResourceManager.GetString("Kaydol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayit.
        /// </summary>
        internal static string Kayit {
            get {
                return ResourceManager.GetString("Kayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        internal static string KayitOl {
            get {
                return ResourceManager.GetString("KayitOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Künye.
        /// </summary>
        internal static string Kunye {
            get {
                return ResourceManager.GetString("Kunye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurum için Başvuru.
        /// </summary>
        internal static string KurumBasvurusu {
            get {
                return ResourceManager.GetString("KurumBasvurusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logonuz buraya gelecek.
        /// </summary>
        internal static string LogonuzBurayaGelecek {
            get {
                return ResourceManager.GetString("LogonuzBurayaGelecek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Şirket logonuzu buraya yükleyin..
        /// </summary>
        internal static string LutfenSırketLogonuzuBurayaYukleyin {
            get {
                return ResourceManager.GetString("LutfenSırketLogonuzuBurayaYukleyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail zaten kayıtlı!.
        /// </summary>
        internal static string MailAdresiKayitli {
            get {
                return ResourceManager.GetString("MailAdresiKayitli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail listesine eklendi..
        /// </summary>
        internal static string MailListesineEklendi {
            get {
                return ResourceManager.GetString("MailListesineEklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail listesine eklenemedi!.
        /// </summary>
        internal static string MailListesineEklenemedi {
            get {
                return ResourceManager.GetString("MailListesineEklenemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Adı.
        /// </summary>
        internal static string MenuAdi {
            get {
                return ResourceManager.GetString("MenuAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Ekle.
        /// </summary>
        internal static string MenuEkle {
            get {
                return ResourceManager.GetString("MenuEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Elemanı Ekle.
        /// </summary>
        internal static string MenuElemanEkle {
            get {
                return ResourceManager.GetString("MenuElemanEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Eleman Listesi.
        /// </summary>
        internal static string MenuElemanListesi {
            get {
                return ResourceManager.GetString("MenuElemanListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü ID.
        /// </summary>
        internal static string MenuID {
            get {
                return ResourceManager.GetString("MenuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menüler.
        /// </summary>
        internal static string Menuler {
            get {
                return ResourceManager.GetString("Menuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Level.
        /// </summary>
        internal static string MenuLevel {
            get {
                return ResourceManager.GetString("MenuLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Listesi.
        /// </summary>
        internal static string MenuListesi {
            get {
                return ResourceManager.GetString("MenuListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Sırası.
        /// </summary>
        internal static string MenuSirasi {
            get {
                return ResourceManager.GetString("MenuSirasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Tipi.
        /// </summary>
        internal static string MenuTip {
            get {
                return ResourceManager.GetString("MenuTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulma Tarihi.
        /// </summary>
        internal static string OlusturulmaTarihi {
            get {
                return ResourceManager.GetString("OlusturulmaTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öne Çıkan Görsel.
        /// </summary>
        internal static string OneCikanGorsel {
            get {
                return ResourceManager.GetString("OneCikanGorsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öne çıkarılmış görsel belirle.
        /// </summary>
        internal static string OneCikanGorselBelirle {
            get {
                return ResourceManager.GetString("OneCikanGorselBelirle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önizleme.
        /// </summary>
        internal static string Onizleme {
            get {
                return ResourceManager.GetString("Onizleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özet.
        /// </summary>
        internal static string Ozet {
            get {
                return ResourceManager.GetString("Ozet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pazara Giriş.
        /// </summary>
        internal static string PazaraGiris {
            get {
                return ResourceManager.GetString("PazaraGiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Kodu.
        /// </summary>
        internal static string PostaKodu {
            get {
                return ResourceManager.GetString("PostaKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozisyon.
        /// </summary>
        internal static string Pozisyon {
            get {
                return ResourceManager.GetString("Pozisyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik avantajlari hakkinda daha fazla bilgi edinin.
        /// </summary>
        internal static string PremiumUyeAvantajlariDetayliBilgi {
            get {
                return ResourceManager.GetString("PremiumUyeAvantajlariDetayliBilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Üyeler.
        /// </summary>
        internal static string PremiumUyeler {
            get {
                return ResourceManager.GetString("PremiumUyeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium-Üyelik.
        /// </summary>
        internal static string PremiumUyelik {
            get {
                return ResourceManager.GetString("PremiumUyelik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Üyelik Ücreti.
        /// </summary>
        internal static string PremiumUyelikUcreti {
            get {
                return ResourceManager.GetString("PremiumUyelikUcreti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Oluştur.
        /// </summary>
        internal static string RaporOlustur {
            get {
                return ResourceManager.GetString("RaporOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Başlık.
        /// </summary>
        internal static string SayfaBaslik {
            get {
                return ResourceManager.GetString("SayfaBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Dili.
        /// </summary>
        internal static string SayfaDili {
            get {
                return ResourceManager.GetString("SayfaDili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Ekle.
        /// </summary>
        internal static string SayfaEkle {
            get {
                return ResourceManager.GetString("SayfaEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        internal static string Sayfalar {
            get {
                return ResourceManager.GetString("Sayfalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Listesi.
        /// </summary>
        internal static string SayfaListesi {
            get {
                return ResourceManager.GetString("SayfaListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Özellikleri.
        /// </summary>
        internal static string SayfaOzellikleri {
            get {
                return ResourceManager.GetString("SayfaOzellikleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seç.
        /// </summary>
        internal static string Sec {
            get {
                return ResourceManager.GetString("Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO Anahtar Kelimeleri.
        /// </summary>
        internal static string SeoAnahtarKelimeleri {
            get {
                return ResourceManager.GetString("SeoAnahtarKelimeleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO Ayarları.
        /// </summary>
        internal static string SeoAyarlari {
            get {
                return ResourceManager.GetString("SeoAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum.
        /// </summary>
        internal static string SifremiUnuttum {
            get {
                return ResourceManager.GetString("SifremiUnuttum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket.
        /// </summary>
        internal static string Sirket {
            get {
                return ResourceManager.GetString("Sirket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Alanı Seç.
        /// </summary>
        internal static string SliderAlaniSec {
            get {
                return ResourceManager.GetString("SliderAlaniSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Ekle.
        /// </summary>
        internal static string SliderEkle {
            get {
                return ResourceManager.GetString("SliderEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Görsel Yükle.
        /// </summary>
        internal static string SliderGorselYukle {
            get {
                return ResourceManager.GetString("SliderGorselYukle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider İçerik Ekle.
        /// </summary>
        internal static string SliderIcerikEkle {
            get {
                return ResourceManager.GetString("SliderIcerikEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Listesi.
        /// </summary>
        internal static string SliderListesi {
            get {
                return ResourceManager.GetString("SliderListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Sırası.
        /// </summary>
        internal static string SliderSirasi {
            get {
                return ResourceManager.GetString("SliderSirasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider URL.
        /// </summary>
        internal static string SliderUrl {
            get {
                return ResourceManager.GetString("SliderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sokak.
        /// </summary>
        internal static string Sokak {
            get {
                return ResourceManager.GetString("Sokak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonuçlar.
        /// </summary>
        internal static string Sonuclar {
            get {
                return ResourceManager.GetString("Sonuclar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı.
        /// </summary>
        internal static string Soyadi {
            get {
                return ResourceManager.GetString("Soyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taslak Olarak Kaydet.
        /// </summary>
        internal static string TaslakOlarakKaydet {
            get {
                return ResourceManager.GetString("TaslakOlarakKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavsiye edebileceğiniz üyeler.
        /// </summary>
        internal static string TavsiyeEdeceginizDigerOdaUyeleri {
            get {
                return ResourceManager.GetString("TavsiyeEdeceginizDigerOdaUyeleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD-IHK üyeliği için başvuruyorum..
        /// </summary>
        internal static string TDIHKUyeligineBasvuruyorum {
            get {
                return ResourceManager.GetString("TDIHKUyeligineBasvuruyorum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temsilci.
        /// </summary>
        internal static string Temsilci {
            get {
                return ResourceManager.GetString("Temsilci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümünü Göster.
        /// </summary>
        internal static string TumunuGoster {
            get {
                return ResourceManager.GetString("TumunuGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ücretsizdir.
        /// </summary>
        internal static string Ucretsizdir {
            get {
                return ResourceManager.GetString("Ucretsizdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ara.
        /// </summary>
        internal static string UyeAra {
            get {
                return ResourceManager.GetString("UyeAra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ekle.
        /// </summary>
        internal static string UyeEkle {
            get {
                return ResourceManager.GetString("UyeEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeler.
        /// </summary>
        internal static string Uyeler {
            get {
                return ResourceManager.GetString("Uyeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelerimiz için bu.
        /// </summary>
        internal static string UyelerimizIcinBu {
            get {
                return ResourceManager.GetString("UyelerimizIcinBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik.
        /// </summary>
        internal static string Uyelik {
            get {
                return ResourceManager.GetString("Uyelik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik Başvurusu.
        /// </summary>
        internal static string UyelikBasvurusu {
            get {
                return ResourceManager.GetString("UyelikBasvurusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Listesi.
        /// </summary>
        internal static string UyeListesi {
            get {
                return ResourceManager.GetString("UyeListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri Gizliliği.
        /// </summary>
        internal static string VeriGizlilik {
            get {
                return ResourceManager.GetString("VeriGizlilik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD-IHK&apos;nın verilerinizi nasıl işlediğine ilişkin bilgiler aşağıdaki sayfalarda bulunabilir.
        /// </summary>
        internal static string VeriIsleme {
            get {
                return ResourceManager.GetString("VeriIsleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş ortağımız GTAI&apos;den iş bilgileri alın. Üyeliğin avantajları hakkında daha fazla bilgi edinin..
        /// </summary>
        internal static string VorteilleMetin {
            get {
                return ResourceManager.GetString("VorteilleMetin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yalnızca.
        /// </summary>
        internal static string Yalnizca {
            get {
                return ResourceManager.GetString("Yalnizca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayımla.
        /// </summary>
        internal static string Yayimla {
            get {
                return ResourceManager.GetString("Yayimla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayınlar.
        /// </summary>
        internal static string Yayinlarimiz {
            get {
                return ResourceManager.GetString("Yayinlarimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yer.
        /// </summary>
        internal static string Yer {
            get {
                return ResourceManager.GetString("Yer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yer Kaldı.
        /// </summary>
        internal static string YerKaldi {
            get {
                return ResourceManager.GetString("YerKaldi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yer, Zaman.
        /// </summary>
        internal static string YerZaman {
            get {
                return ResourceManager.GetString("YerZaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yonetim Paneli.
        /// </summary>
        internal static string YonetimPaneli {
            get {
                return ResourceManager.GetString("YonetimPaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.000 € / yıl.
        /// </summary>
        internal static string _10BinEuroYillik {
            get {
                return ResourceManager.GetString("10BinEuroYillik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 koltuktan birini ister misiniz.
        /// </summary>
        internal static string _10KoltuktanBirisiniIsterMisiniz {
            get {
                return ResourceManager.GetString("10KoltuktanBirisiniIsterMisiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 Milyon € kadar.
        /// </summary>
        internal static string _20MilyonEuroKadar {
            get {
                return ResourceManager.GetString("20MilyonEuroKadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 Milyon € üzerinde.
        /// </summary>
        internal static string _20MilyonEuroUzerinde {
            get {
                return ResourceManager.GetString("20MilyonEuroUzerinde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Milyon € kadar (1,200 € / yıl).
        /// </summary>
        internal static string _5MilyonEuroKadar {
            get {
                return ResourceManager.GetString("5MilyonEuroKadar", resourceCulture);
            }
        }
    }
}
